; Configure which static analysis checks are enabled
[analysis.config.StaticAnalysisConfig]
; Check variable, class, struct, interface, union, and function names against the Phobos style guide
style_check="disabled"
; Checks that opEquals, opCmp, toHash, and toString are either const, immutable or inout.
object_const_check="enabled"
; Checks for unused variables
unused_variable_check="disabled"
; Check for properly documented public functions (Returns, Params)
properly_documented_public_functions="disabled"
; Module filters for selectively enabling and disabling individual checks
[analysis.config.ModuleFilters]
; Exclude/Import modules
undocumented_declaration_check="-gccjit.bindings"
